In [2]:
import numpy as np
array1 = np.array([1,2,3], dtype='int64')
array1
array2 = array1.astype('float64')
array2
array3 = np.array([[1,2],[3,5]], dtype='int64')
array3
array4 = np.arange(4)
array4
arrayones = np.ones(5)
arrayones
arrayonesas = np.ones_like(array4)
arrayonesas
matrixId = np.identity(5)
matrixId





array([-0.88638072,  0.02109864,  0.20820352,  0.04391589,  1.04924483])

In [3]:
#array arithmetics
a1 = np.array([1,7,3])
a2 = np.array([4,5,6])
a1 + a2
a1*a2
5 * a1
a1 > a2

#indexing and slicing
arr = np.array([6,4,9,2,5,7])
arrnew = arr[3:5]
arrnew

#now see how modifying arrnew makes the same changes on the respective sliced elements in the original array:
arrnew[:] = 73 #synthax for modifying an entire list of elements
arrnew
arr
"""""this is because numpy does not copy information from other arrays when you slice them, they just get the same
pieces of memory from the original, the reason for this is that it would be very costly to create new spaces of memory
for each array sliced"""

#still, there is a way to copy a slice of an array...
copied = arr[2:5].copy()
arr[3:5] = [4,5]
arr
copied
# note that they are different




array([-0.07871041, -0.45874573,  0.12229248,  0.11795339,  0.70979855])

In [4]:
#lets see how to access 'multi-dimensional arrays'
marray = np.array([[1,2,3],[54,6,3],[73,37,12]], dtype='int64')
#see th two ways to access the array...
marray[1][2]
marray[1,2] #easier to access: first integer stands for the first element of the list, second for the second element inside


#indexing with boolean values
randnormalmat = np.random.randn(6,5)#genera un array de dimension 3x2 que posee valores aleatorios de una distribucion normal estandar (media de cero y variacion aproximada de +-1)

names = np.array(['marco', 'carlos', 'marco', 'belisario', 'bautista', 'marco'], dtype='string')
randnormalmat[names=='marco'] #como los unicos elementos que cumplen con la condicion son el primero, el tercero y el sexto
#entonces nos devuelven los indices 0, 2 y 5 del array con valores normales. esto es, la primera tercera y sexta fila.
'''you can also use multiple conditions with | and &'''
randnormalmat[(names=='belisario') | (names =='carlos'), 2:] = 0 # para los elementos de igual indice que el carlos o belisario, asignar el valor cero desde el tercer elemento en adelante

randnormalmat

names == 'marco'

arr = np.arange(32).reshape((8, 4))
arr2 = arr.T 
arr2 #transposed arr copy



array([ 0.06520965,  0.19854982, -0.73984145, -2.16522346,  0.33544361])

In [5]:
## antes de hacer lo siguiente, repasá y practica un poco el slicing y el indexing y transposicion

#universal functions
arai1 = np.random.randn(5)

arai2 = np.random.randn(5)
arai1, arai2
np.floor(arai1) #unary universal function, applied to each element of the array

np.multiply(arai1, arai2) #binary ufunc, multiplies the two given arrays element by element


array([-2.99753192, -0.0579698 , -1.2666711 , -0.06712349,  0.32924504])